development:
adapter: postgresql
encoding: unicode
database: andrew_sound_manager_development
pool: 5
username: ajwithem
password:

test:
adapter: postgresql
encoding: unicode
database: andrew_sound_manager_test
pool: 5
username: ajwithem
password: