development:
  adapter: postgresql
  encoding: unicode
  database: asm_development
  pool: 5
  username: ajwithem
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: asm_test
  pool: 5
  username: ajwithem
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: asm_production
  pool: 5
  username: ajwithem
  password: